general:
  me: config.yml
  BATCH_SIZE: 30
  split_ratio: 0.7
  data_information: False
  model: BERT # (RNN, LSTM, GRU, BERT)

RNN:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: True
  dropout: 0.2
  last_hidden: True

LSTM:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: False
  dropout: 0.2
  last_hidden: False

GRU:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: True
  dropout: 0.2
  last_hidden: True

training:
  EPOCH_NUM: 2
  learning_rate: 0.001
  weight_decay: 1e-5
