general:
  me: config.yml
  BATCH_SIZE: 30
  split_ratio: 0.7
  data_information: False
  model: GRU # (RNN, LSTM, or GRU)

RNN:
  hidden_size: 55
  number_of_layers: 2
  bidirectional: True
  dropout: 0.2
  last_hidden: True

LSTM:
  hidden_size: 55
  number_of_layers: 2
  bidirectional: True
  dropout: 0.2
  last_hidden: True

GRU:
  hidden_size: 55
  number_of_layers: 2
  bidirectional: True
  dropout: 0.2
  last_hidden: True

training:
  EPOCH_NUM: 100
  learning_rate: 0.001
