general:
  me: config.yml
  BATCH_SIZE: 50
  split_ratio: 0.7
  data_information: False
  model: GRU # (RNN, LSTM, GRU, BERT)

RNN:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: False
  dropout: 0.2
  last_hidden: False
  learning_rate: 0.0007

LSTM:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: False
  dropout: 0.2
  last_hidden: False
  learning_rate: 0.0007

GRU:
  hidden_size: 16
  number_of_layers: 2
  bidirectional: False
  dropout: 0.2
  last_hidden: False
  learning_rate: 0.0007

BERT:
  learning_rate: 2e-5

training:
  EPOCH_NUM: 100
  weight_decay: 1e-4
